name: CI-test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: v1-gradle-caches-${{ hashFiles('settings.gradle.kts') }}-${{ hashFiles('build.gradle.kts') }}-${{ hashFiles('gradle.properties') }}
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/wrapper
        key: v1-gradle-wrapper-${{ hashFiles('settings.gradle.kts') }}-${{ hashFiles('build.gradle.kts') }}-${{ hashFiles('gradle.properties') }}
    - name: DL all dependencies
      run: ./gradlew resolveDependencies
    - name: set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: ktlint and verify plugin
      run: ./gradlew ktlintCheck verifyPlugin --no-daemon --max-workers 2
    - name: test
      run: ./gradlew test jacocoTestReport --no-daemon --max-workers 2
    - name: upload coverage
      uses: codecov/codecov-action@v1