name: CI-test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: v1-gradle-caches-${{ hashFiles('settings.gradle.kts') }}-${{ hashFiles('build.gradle.kts') }}-${{ hashFiles('gradle.properties') }}
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/wrapper
        key: v1-gradle-wrapper-${{ hashFiles('settings.gradle.kts') }}-${{ hashFiles('build.gradle.kts') }}-${{ hashFiles('gradle.properties') }}
    - name: set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: DL all dependencies
      run: ./gradlew resolveDependencies
    - name: ktlint and verify plugin
      run: ./gradlew ktlintCheck verifyPlugin --no-daemon --max-workers 2
    - name: test
      run: ./gradlew test jacocoTestReport --no-daemon --max-workers 2
    - name: upload coverage
      uses: codecov/codecov-action@v1

  beta-release:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: startswith(github.ref, 'refs/tags/beta-')
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: v1-gradle-caches-${{ hashFiles('settings.gradle.kts') }}-${{ hashFiles('build.gradle.kts') }}-${{ hashFiles('gradle.properties') }}
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: v1-gradle-wrapper-${{ hashFiles('settings.gradle.kts') }}-${{ hashFiles('build.gradle.kts') }}-${{ hashFiles('gradle.properties') }}
      - name: get the version
        id: get_version
        run: echo ::set-output name=version::${github_ref/refs\/tags\//}
      - name: Release
        env:
          TAG_NAME: ${{ github.ref }}
          HUB_TOKEN: ${{ secrets.HUB_TOKEN }}
        run: ./gradlew buildPlugin publishPlugin -DVERSION=${TAG_NAME#refs/tags/beta-} -DCHANNELS=beta

  release:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/release-')
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: v1-gradle-caches-${{ hashFiles('settings.gradle.kts') }}-${{ hashFiles('build.gradle.kts') }}-${{ hashFiles('gradle.properties') }}
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: v1-gradle-wrapper-${{ hashFiles('settings.gradle.kts') }}-${{ hashFiles('build.gradle.kts') }}-${{ hashFiles('gradle.properties') }}
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Release
        env:
          TAG_NAME: ${{ github.ref }}
          HUB_TOKEN: ${{ secrets.HUB_TOKEN }}
        run: ./gradlew buildPlugin publishPlugin -DVERSION=${TAG_NAME#refs/tags/release-} -DCHANNELS=default
